### ISSUE TITLE
Branch widget is broken

### ISSUE THREAD

**Issue by florianm** [clint-tseng/odkbuild#19]
When dragging and dropping the branch input widget into the form area, only a grey box appears, but there are no properties to set. Happening in Chrome v24, Firefox v17. If there are some browser extensions blocking it, maybe a hint would be useful to disable them on ODK Build. If adding a branch requires an action different to drag and drop (as with the other widgets), a hint would be great.
Thanks for the great app, very useful!

**Comment by ByronJames** [comment]
Branch isn't working at all. Would be handy if it did! Awesome tools by the way.

**Comment by clint-tseng** [comment]
Branch no longer appears in the UI. We recommend a combination of Group and Relevance logic instead. Perhaps Branch will come back someday if I can figure out a way to make it make sense in all cases.
