### ISSUE TITLE
User story: Being logged into Google (e.g. Gmail) within same browser session prevents publishing forms to ODK aggregate

### ISSUE THREAD

**Issue by florianm** [clint-tseng/odkbuild#21]
When e.g. Gmail is running in another browser tab, ODK Build > File > Publish to Aggregate... will fail with an authentication error. 
Related: Logging into an ODK Aggregate instance on google appspot will log you out from any other Google sessions within the same browser window and vice versa. 
Took me a while to figure out, and not an issue with ODK Build, but maybe worth a mention in Help  > troubleshooting?

**Comment by clint-tseng** [comment]
Currently, ODK Aggregate export is entirely broken as it no longer has an OAuth 1.0 bridge.
The likely replacement strategy will inherently resolve this issue as it doesn't depend directly on browser authentication, so I'm going to close it.
