### ISSUE TITLE
Publish to Aggregate

### ISSUE THREAD

**Issue by mkhines** [clint-tseng/odkbuild#32]
When I hit publish to aggregate and enter in my appspot.com address, I get an internal server error.  I believe this is a bug?

**Comment by nlundman** [comment]
I receive this error doing the same, as well. I just started working with ODK so have a learning curve ahead...But if anyone knows why this is happening, I'd appreciate some tips on how to publish to aggregate without the error. Thanks!

**Comment by florianm** [comment]
Having the same error, I suspect the authentication might be failing.

@nlundman @mkhines you can run File > Export to XML to download the XML config for the form, then in Aggregate > Form Management > Add New Form and upload the XML file.

**Comment by clint-tseng** [comment]
A fix for this is being deployed now..

**Comment by clint-tseng** [comment]
Okay, I believe export to Aggregate should work again. Be warned that Aggregate will reject you outright if your form is not valid, but otherwise everything should be copacetic. Please give it a shot and let me know what you see.

**Comment by clint-tseng** [comment]
I've run through this quite a few times now, and I'm confident that it works. Please feel free to reopen this issue or open a new one if you see otherwise.

**Comment by florianm** [comment]
@clint-tseng apologies for my delay in testing (was in the field testing ODK) - publish to Aggregate works perfectly on my end, thanks for the fix!
