### ISSUE TITLE
Using ODK Collect -Taking Picture Reboots  Acer A500 Tablet - Android (4.0.3)

### ISSUE THREAD

**Issue by jegs223** [clint-tseng/odkbuild#35]
Created 2 forms using Build and upload to Aggregate. The forms have an image field. I use Collect to access the forms on my Acer A500 Android 4.0.3 Tablet. All other field works fine but when i attempt to use the picture field - as soon as I take the picture, my tablet is rebooted. This happens with both forms. The camera works fine with other applications.

The image field is optional - without the picture, the forms are fine - I can enter data, finalize and submit.

The same thing happens each time I attempt to take picture to attached to the image field.

 Attaching an image works fine.

**Comment by clint-tseng** [comment]
If this is still an issue, please report it on the Collect issues page instead: https://github.com/opendatakit/collect/issues
