### ISSUE TITLE
Error while creating branch component 

### ISSUE THREAD

**Issue by princemjain** [clint-tseng/odkbuild#40]
Hi team,
I am trying to create a skip logic(refering to branch) in my form but i am getting a error in my console.
Error as follows.

Chrome 
Uncaught TypeError: Cannot read property 'value' of undefined

Firefox
TypeError: h.name is undefined

any solution for above error.

Thanks in advance
Prince M Jain

**Comment by clint-tseng** [comment]
This item is no longer in the UI. We recommend the use of a Group component with a Relevance expression instead.
